### PR TITLE
Report termination errors after typechecking

### LINKED ISSUE #2293: Incomprehensible error message when the number of patterns doesn't match the type
Typechecking the program
```
module tyomit;

type List A := nil | cons A (List A);

map {A B} (f : A → B) : List A → List B
  | nil := nil
  | cons h t := cons (f h) (map f t);
```
results is
```
/Users/heliax/Documents/progs/juvix/tyomit.juvix:5:1-4: error:
The function map fails the termination checker.
```
The error should be that the number of patterns doesn't match the type.

Maybe we should just check e.g. at scoping whether all clauses have the same number of pattern. For now, we don't support clauses with different numbers of patterns anyway.

### LINKED ISSUE #2319: Expressions are not checked for termination in the repl
E.g. typing the following in the repl causes it to loop:
```
let x : Type := x in 1
```

### PR DESCRIPTION
**Pull request by janmasrovira**
- Closes #2293.
- Closes #2319 

I've added an effect for termination. It keeps track of which functions failed the termination checker, which is run just after translating to Internal. During typechecking, non-terminating functions are not normalized. After typechecking, if there is at least one function which failed the termination checker, an error is reported.
Additionally, we now properly check for termination of functions defined in a let expression in the repl.

### CODE REVIEW

File: src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Data/TerminationState.hs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+import Juvix.Compiler.Internal.Language
+import Juvix.Prelude
+
+data IsTerminating
+  = -- | Has been checked for termination.
+    TerminatingChecked
+  | -- | Has been checked for termination but failed.
+    TerminatingFailed
+  | -- | Has been marked as terminating in the source code.
+    TerminatingMarked
```
Comment (jonaprieto) [inline src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Data/TerminationState.hs:21]: Remove this.

File: src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Checker.hs [hunk 2]
```diff
@@ -1,45 +1,111 @@
...
+  FunctionTermination :: FunctionRef -> Termination m IsTerminating
+
+makeSem ''Termination
+
+functionIsTerminating :: (Members '[Termination] r) => FunctionRef -> Sem r Bool
+functionIsTerminating = fmap terminates . functionTermination
+  where
+    terminates :: IsTerminating -> Bool
+    terminates = \case
+      TerminatingMarked -> True
```
Comment (jonaprieto) [inline src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Checker.hs:36]: Remove this as well.

File: src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Data/TerminationState.hs (hunk 1 above)
Comment (janmasrovira) [reply src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Data/TerminationState.hs]: done

File: src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Checker.hs (hunk 2 above)
Comment (janmasrovira) [reply src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/Termination/Checker.hs]: done

**Review by jonaprieto — APPROVED** [review]
