### PR TITLE
Fix instance axiom bug

### LINKED ISSUE #2438: Crash `impossible` if an instance decl. contains an axiom
The following code crashes the compiler v0.5.3-c3fca68.

```
module Bug;

trait
type T := t;

axiom <body> : T;

instance
FIXME : T := <body>;

end;
```

I'm getting the following error.

```
juvix: impossible
CallStack (from HasCallStack):
  error, called at src/Juvix/Prelude/Base.hs:389:14 in juvix-0.5.2-FNh6WsMNvIEJlM3XwOn8Aq:Juvix.Prelude.Base
  impossible, called at src/Juvix/Compiler/Internal/Translation/FromConcrete.hs:275:20 in juvix-0.5.2-FNh6WsMNvIEJlM3XwOn8Aq:Juvix.Compiler.Internal.Translation.FromConcrete

 *  The terminal process "/opt/homebrew/bin/fish '-l', '-c', 'juvix --internal-build-dir /var/folders/7g/nycqh9td3j5_qcn7h8fmh4wm0000gn/T/.juvix-buildLd0LkT  typecheck /Users/jonaprieto/anoma/juvix-docs/docs/reference/language/Bug.juvix'" failed to launch (exit code: 1). 
```

### PR DESCRIPTION
**Pull request by lukaszcz**
* Closes #2438

### CODE REVIEW

File: src/Juvix/Compiler/Internal/Extra/Base.hs [hunk 1]
```diff
@@ -183,6 +183,11 @@ instance HasExpressions MutualStatement where
   leafExpressions f = \case
     StatementFunction d -> StatementFunction <$> leafExpressions f d
     StatementInductive d -> StatementInductive <$> leafExpressions f d
+    StatementAxiom d -> StatementAxiom <$> leafExpressions f d
+
+instance HasExpressions AxiomDef where
+  leafExpressions _ ax@AxiomDef {} = do
```
Comment (janmasrovira) [inline src/Juvix/Compiler/Internal/Extra/Base.hs:189]: It should process the axiom type

Comment (lukaszcz) [reply src/Juvix/Compiler/Internal/Extra/Base.hs]: Done

**Review by janmasrovira — APPROVED** [review]
