### PR TITLE
Fix #2924. Use MegaParsec scanner for Markdown files

### LINKED ISSUE #2924: Typecheck fails on Juvix Markdown files containing the word "import".
Thanks to @heindel, who just couldn't resist adding "important" things to the specs, we finally noticed the issue. 

To reproduce the issue:

```
$ cat Hi.juvix.md
What is important is seldom urgent. 
```

The type checker reports:

```
juvix-v0.6.4 typecheck Hi.juvix.md 
/Users/jonaprieto/anoma/juvix/tests/positive/Markdown/Hi.juvix.md:0:8-17: error:
The module ant does not exist.
It should be in /Users/jonaprieto/anoma/juvix/tests/positive/ant.juvix
or in one of the dependencies:
• .juvix-build/stdlib/
```

### PR DESCRIPTION
**Pull request by jonaprieto**
This PR addresses a bug/missing case present since v0.6.2, introduced specifically by 

- PR #2779, 

That PR involves detecting imports in Juvix files before type checking, and that's the issue.
Detecting/scanning imports is done by running a flat parser (which ignores the Juvix Markdown structure) and when it fails, it runs a Megaparser parse. So, for simplicity,
we could just continue using the same Megaparser as before for Juvix Markdown files.

### CODE REVIEW

File: src/Juvix/Compiler/Concrete/Translation/ImportScanner/FlatParse.hs [hunk 1]
```diff
@@ -12,7 +12,9 @@ import Juvix.Prelude.FlatParse qualified as FP
 import Juvix.Prelude.FlatParse.Lexer qualified as L
 
 scanBSImports :: Path Abs File -> ByteString -> Maybe ScanResult
-scanBSImports fp = fromResult . scanner fp
+scanBSImports fp
+  | isJuvixFile fp = fromResult . scanner fp
```
Comment (janmasrovira) [inline src/Juvix/Compiler/Concrete/Translation/ImportScanner/FlatParse.hs:16]:
```suggestion
   -- FlatParse only supports .juvix files
  | isJuvixFile fp = fromResult . scanner fp
```

**Review by janmasrovira — COMMENTED** [review]
I suggest adding a comment to clarify

**Review by janmasrovira — APPROVED** [review]
