### PR TITLE
Fix Core-To-Geb translation

### LINKED ISSUE #1814: Add missing object information for left and right Geb morphisms
Follow up:

- https://github.com/anoma/geb/issues/53)

### PR DESCRIPTION
**Pull request by jonaprieto**
This PR adds support for all recent changes in GEB introduced by:
- https://github.com/anoma/geb/pull/70
- Closes #1814

Summary:

- [x] Add LeftInj, RightIng, and Absurd types in GEB language
  - [x] Fix FromCore translation for the new data types and minor code styling issues.
  - [x] Fix GEB-STLC type inference and checking
- [X] Add support for evaluating typed morphism "(typed ...)" in the Geb repl and .geb files.
- [x] Simplify a bit the Geb parser
- [x] Fix `dev geb check` command
- [x] Type check files in `tests/Geb/positive`

After this PR, we should include interval location for Geb terms to facility debugging type-checking errors.

### CODE REVIEW

File: src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs [hunk 1]
```diff
@@ -237,28 +254,64 @@ fromCore tab = case tab ^. Core.infoMain of
...
+      _ ->
+        error "wrong builtin application argument number"
 
     convertConstr :: Core.Constr -> Trans Morphism
     convertConstr Core.Constr {..} = do
-      prod <- mkProd
-      return (foldr ($) prod (replicate tagNum MorphismRight))
+      args <- convertProduct _constrArgs
+      unless (tagNum < length constructors) $
+        error "constructor tag out of range"
```
Comment (lukaszcz) [inline src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs:275]: This can never be false unless there is a bug in `mkConstructors` or `convertInductive`.

File: src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs [hunk 2]
```diff
@@ -322,7 +380,15 @@ fromCore tab = case tab ^. Core.infoMain of
...
     convertCase Core.Case {..} = do
       if
-          | null branches -> MorphismAbsurd <$> convertNode _caseValue
+          | null branches -> do
+              x <- convertNode _caseValue
+              let ty = convertInductive _caseInductive
+              return $
+                MorphismAbsurd
+                  Absurd
+                    { _absurdType = ty,
```
[the remark this answers is not in the document]
Comment (lukaszcz) [reply src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs:389]: Use: `convertType (Info.getNodeType ...)`

**Review by lukaszcz — CHANGES_REQUESTED** [review]
Fix the Absurd case

File: src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs [hunk 3]
```diff
@@ -322,7 +380,14 @@ fromCore tab = case tab ^. Core.infoMain of
     convertCase :: Core.Case -> Trans Morphism
     convertCase Core.Case {..} = do
       if
-          | null branches -> MorphismAbsurd <$> convertNode _caseValue
+          | null branches -> do
+              x <- convertNode _caseValue
+              return $
+                MorphismAbsurd
+                  Absurd
+                    { _absurdType = codomainType,
```
Comment (lukaszcz) [inline src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs:388]: So why didn't you fix this? This will always give an error because `branches` is empty.

Comment (lukaszcz) [reply src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs:388]: `_absurdType = convertType (Info.getInfoType _caseInfo)`

Comment (jonaprieto) [reply src/Juvix/Compiler/Backend/Geb/Translation/FromCore.hs:388]: Wait, I did. It's very strange.

**Review by lukaszcz — APPROVED** [review]
