### PR TITLE
Use stderr for errors in the runtime

### LINKED ISSUE #1902: Make `trace` and `fail` write to `stderr`
Currently, `trace` and `fail` write to `stdout` (when compiled down to WASM/native). Since these are debugging functions, they should write to `stderr`. This requires fixing the runtime.

### PR DESCRIPTION
**Pull request by lukaszcz**
* Closes #1902

### CODE REVIEW

File: test/Runtime/Base.hs [hunk 1]
```diff
@@ -24,6 +24,30 @@ clangCompile mkClangArgs inputFile outputFile execute step =
         execute outputFile'
     )
 
+readProcess :: FilePath -> [String] -> Text -> IO Text
```
Comment (janmasrovira) [inline test/Runtime/Base.hs:27]: Explain briefly what this function does

Comment (lukaszcz) [reply test/Runtime/Base.hs:27]: The same as `P.readProcess` but instead of inheriting `stderr` redirects it to the child's `stdout`. I'll add a comment.

File: test/Runtime/Base.hs [hunk 2]
```diff
@@ -24,6 +24,32 @@ clangCompile mkClangArgs inputFile outputFile execute step =
         execute outputFile'
     )
 
+-- The same as `P.readProcess` but instead of inheriting `stderr` redirects it
```
Comment (janmasrovira) [inline test/Runtime/Base.hs:27]:
```suggestion
-- | The same as `P.readProcess` but instead of inheriting `stderr` redirects it
```

**Review by janmasrovira — APPROVED** [review]

**Review by janmasrovira — APPROVED** [review]
