### PR TITLE
Typcheck imports before statements

### LINKED ISSUE #2248: Typecheck error when using 'type aliases' via imports (regression since 0.4.1)
I spotted this behaviour change in the type checker when trying to compile the `containers` library with juvix HEAD. Specifically there's a type error on this line https://github.com/anoma/juvix-containers/blob/851119ca6b4e94fab0ce7353c4b9d2930f53cc56/Data/Map.juvix#L36

```
/containers/Data/Map.juvix:36:20-25: error:
The expression Set.empty {_} has type:
  AVLTree (Binding _ _)
but is expected to have type:
  Set (Binding _ _)
make: *** [build/Map] Error 1
```

This behaviour change was introduced by (analysis using git bisect):
* https://github.com/anoma/juvix/pull/2219

For a more minimal reproduction, consider the following two modules:

Bug.juvix
```
module Bug;

type A := a : A;

B : Type;
B := A;

type C := mkC : B -> C;
```

Import.juvix
```
module Import;

import Bug open;

c : C := mkC a;
```

Run `juvix typecheck Import.juvix`

```
/Import.juvix:5:14-15: error:
The expression a has type:
  A
but is expected to have type:
  B
```

Note that the following type checks fine, so the import is necessary to trigger the bug:

```
module NoBug;

type A := a : A;

B : Type;
B := A;

type C := mkC : B -> C;

c : C := mkC a;
```

Import.juvix typechecks fine with Juvix v0.4.1.

### PR DESCRIPTION
**Pull request by janmasrovira**
- closes #2248

### CODE REVIEW

File: src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs [hunk 1]
```diff
@@ -48,20 +48,25 @@ checkModuleNoCache ::
   Sem r Module
 checkModuleNoCache (ModuleIndex Module {..}) = do
   _moduleBody' <-
-    (evalState (mempty :: NegativeTypeParameters) . checkModuleBody) _moduleBody
+    evalState (mempty :: NegativeTypeParameters)
+      . checkModuleBody
+      $ _moduleBody
+  _moduleExamples <- mapM checkExample _moduleExamples
```
Comment (paulcadman) [inline src/Juvix/Compiler/Internal/Translation/FromInternal/Analysis/TypeChecking/Checker.hs:54]: Were the examples not checked before?

**Review by paulcadman — APPROVED** [review]
