### PR TITLE
Fix 'function not found' error in `juvix eval`

### LINKED ISSUE #2176: Evaluating a file without main function crashes
Trying to evaluate
```
module prog;

import Stdlib.Prelude open;

end;
```
with `juvix eval prog.juvix`, gives:
```
juvix: function not found
CallStack (from HasCallStack):
  error, called at src/Juvix/Prelude/Base.hs:352:9 in juvix-0.3.5-9Z2pTCHMwi87oYw3JAmjVz:Juvix.Prelude.Base
  error, called at app/Commands/Eval.hs:41:11 in main:Commands.Eval
```

### PR DESCRIPTION
**Pull request by lukaszcz**
* Closes #2176

### CODE REVIEW

File: app/Commands/Eval.hs [hunk 1]
```diff
@@ -15,11 +15,16 @@ runCommand opts@EvalOptions {..} = do
...
-            | isJust (_evalSymbolName) -> getNode' tab (selInfo tab)
-            | otherwise -> getNode' tab (mainInfo tab)
-  Eval.evalAndPrint opts tab evalNode
+            | isJust (_evalSymbolName) -> getNode tab (selInfo tab)
+            | otherwise -> getNode tab (mainInfo tab)
+  case mevalNode of
+    Just evalNode ->
+      Eval.evalAndPrint opts tab evalNode
+    Nothing -> do
+      let name = fromMaybe "main" _evalSymbolName
```
Comment (janmasrovira) [inline app/Commands/Eval.hs:26]:
```
import Juvix.Extra.Strings qualified as Str
```

```suggestion
      let name = fromMaybe Str.main _evalSymbolName
```

**Review by janmasrovira — COMMENTED** [review]
Let's add a test

**Review by janmasrovira — DISMISSED** [review]

**Review by paulcadman — APPROVED** [review]
